export { default as Home } from './Home/Home'
export { default as Hotels } from './Hotels/Hotels'
export { default as Hotel } from './Hotel/Hotel'
export { default as Login } from './Auth/Login'
export { default as Register} from './Auth/Register'